// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcn29CsnMNDcwLvRRUps99gYcLWCAUf_U',
    appId: '1:835377572606:web:2503ce23ce45b1455193af',
    messagingSenderId: '835377572606',
    projectId: 'skool-e4bb7',
    authDomain: 'skool-e4bb7.firebaseapp.com',
    storageBucket: 'skool-e4bb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpm3qtGdwDPjMRaXGViJmsILdIgVOlOPo',
    appId: '1:835377572606:android:9f883e1ed7750aa15193af',
    messagingSenderId: '835377572606',
    projectId: 'skool-e4bb7',
    storageBucket: 'skool-e4bb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgfR44i80hQkqIhMKUTfrZmLchHivIRp8',
    appId: '1:835377572606:ios:6d249c4a54dd03c75193af',
    messagingSenderId: '835377572606',
    projectId: 'skool-e4bb7',
    storageBucket: 'skool-e4bb7.firebasestorage.app',
    iosBundleId: 'com.example.skool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgfR44i80hQkqIhMKUTfrZmLchHivIRp8',
    appId: '1:835377572606:ios:6d249c4a54dd03c75193af',
    messagingSenderId: '835377572606',
    projectId: 'skool-e4bb7',
    storageBucket: 'skool-e4bb7.firebasestorage.app',
    iosBundleId: 'com.example.skool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcn29CsnMNDcwLvRRUps99gYcLWCAUf_U',
    appId: '1:835377572606:web:fa729d4dccabc8205193af',
    messagingSenderId: '835377572606',
    projectId: 'skool-e4bb7',
    authDomain: 'skool-e4bb7.firebaseapp.com',
    storageBucket: 'skool-e4bb7.firebasestorage.app',
  );
}
